name: kite
version: '0.3.1'
summary: Multi-cloud Infrastructure as Code CLI - write once, deploy anywhere
description: |
  Kite is a multi-cloud Infrastructure as Code (IaC) tool that lets you define
  cloud resources using a simple .kite language and deploy them to AWS, GCP,
  or Azure.

  Features:
  • Write once, provision anywhere - same code works across cloud providers
  • Simple, readable syntax for defining infrastructure
  • Native CLI with fast startup (GraalVM native image)
  • Support for AWS, Google Cloud, and Microsoft Azure

  Get started:
    kite init myproject
    kite plan
    kite apply

  Documentation: https://kitelang.cloud/docs
  Source: https://github.com/kitecorp/kite-language

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: [amd64]
  - build-on: [arm64]

apps:
  kite:
    command: bin/kite
    plugs:
      - home
      - network
      - network-bind

parts:
  kite:
    plugin: dump
    source:
      - on amd64: https://github.com/kitecorp/kite-cli/releases/download/0.3.1/kite-0.3.1-linux-amd64.tar.gz
      - on arm64: https://github.com/kitecorp/kite-cli/releases/download/0.3.1/kite-0.3.1-linux-arm64.tar.gz
