name: kite
version: '0.2.3'
summary: Multi-cloud Infrastructure as Code CLI
description: |
  |
  Kite is a multi-cloud Infrastructure as Code (IaC) tool that provides
  a "write once, provision anywhere" approach using a custom .kite language
  for defining cloud resources that can be deployed to AWS, GCP, or Azure.

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: [amd64]
    run-on: [amd64]
  - build-on: [arm64]
    run-on: [arm64]

apps:
  kite:
    command: bin/kite
    plugs:
      - home
      - network
      - network-bind

parts:
  kite:
    plugin: dump
    source:
      - on amd64: https://github.com/kitecorp/kite-cli/releases/download/0.2.3/kite-0.2.3-linux-amd64.tar.gz
      - on arm64: https://github.com/kitecorp/kite-cli/releases/download/0.2.3/kite-0.2.3-linux-arm64.tar.gz
